-- пользователь для миграций
CREATE USER flyway_user WITH PASSWORD 'secret_flyway_pass';

GRANT CONNECT ON DATABASE msdb TO flyway_user;
GRANT USAGE ON SCHEMA public TO flyway_user;

ALTER SCHEMA public OWNER TO flyway_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO flyway_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO flyway_user;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO flyway_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO flyway_user;
