spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/msdb?stringtype=unspecified
    username: app_user
    password: secret_app_pass

  flyway:
    enabled: true
    user: flyway_user
    password: secret_flyway_pass
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 3

logging:
  level:
    org.springframework.boot.autoconfigure.flyway: DEBUG
    org.flywaydb: DEBUG