spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/msdb?stringtype=unspecified
    username: app_user
    password: secret_app_pass

logging:
  level:
    org.springframework.boot.autoconfigure.flyway: DEBUG
    org.flywaydb: DEBUG