spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/msdb?stringtype=unspecified
    username: app_user
    password: secret_app_pass

  flyway:
    enabled: false

logging:
  level:
    root: INFO
    org.flywaydb: INFO
