# src/main/resources/application-docker.yml
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/msdb
    username: app_user          # тот же пользователь, которого создаёт init-скрипт
    password: secret            # пароль из V2__create_app_user.sql
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate        # схема уже есть – только проверяем
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true               # включено по умолчанию, но явно не помешает
    baseline-on-migrate: true   # ← ключевое: если history-таблицы нет – создаёт её
    baseline-version: 0         # ← помечает текущее состояние базы как «версия 0»
    # locations: classpath:db/migration   # (остается дефолт)

server:
  port: 8080

logging:
  level:
    root: INFO
    org.flywaydb: INFO
